CREATE SCHEMA IF NOT EXISTS CALCULATOR;
SET SCHEMA CALCULATOR;

CREATE TABLE IF NOT EXISTS POSTCODES
(
    ID        BIGINT PRIMARY KEY,
    POSTCODE  VARCHAR(20),
    LATITUDE  NUMBER(20, 10),
    LONGITUDE NUMBER(20, 10)
) AS SELECT * FROM CSVREAD('classpath:ukpostcodes.csv');

CREATE INDEX IF NOT EXISTS IDX_PC_POSTCODE ON POSTCODES(POSTCODE);

CREATE TABLE IF NOT EXISTS DISTANCES
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    SRC_POSTCODE VARCHAR(20),
    SRC_LATITUDE  NUMBER(20, 10),
    SRC_LONGITUDE NUMBER(20, 10),
    DEST_POSTCODE VARCHAR(20),
    DEST_LATITUDE  NUMBER(20, 10),
    DEST_LONGITUDE NUMBER(20, 10),
    DISTANCE  NUMBER(20, 10),
    CREATED_DATE DATETIME,
    UPDATED_DATE DATETIME
);

CREATE INDEX IF NOT EXISTS IDX_DISTANCES_CREATED_DATE ON DISTANCES(CREATED_DATE);